# Generated by Django 4.2.5 on 2023-09-25 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student_app', '0002_alter_student_marks_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='hello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_app.student')),
            ],
        ),
    ]
