# Generated by Django 4.2.5 on 2023-09-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_id', models.IntegerField()),
                ('fac_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='hello',
        ),
    ]
