# Generated by Django 5.0.6 on 2024-07-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_records',
            name='email',
            field=models.EmailField(default='Enter your email here', max_length=254, unique=True),
        ),
    ]
