# Generated by Django 4.2.5 on 2023-09-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_remove_faculty_records_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_records',
            name='fac_id',
            field=models.IntegerField(default=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
