# Generated by Django 4.2.5 on 2023-12-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GtuExam',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, unique=True)),
                ('sub_code', models.CharField(default='0000000', max_length=7)),
                ('sub_branch_code', models.CharField(default='16', max_length=2)),
                ('sub_sem', models.IntegerField(default=0)),
                ('sub_academic_term', models.CharField(max_length=5)),
                ('sub_session', models.CharField(max_length=6)),
                ('sub_pdf', models.FileField(upload_to='home/pdfs/exam')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Syllabus',
            fields=[
                ('sub_id', models.CharField(default='11-1111111', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('sub_name', models.CharField(max_length=100)),
                ('sub_code', models.CharField(max_length=7)),
                ('session', models.CharField(choices=[('WINTER', 'Winter'), ('SUMMER', 'Summer')], default='SUMMER', max_length=50)),
                ('sub_branch_code', models.CharField(default='16', max_length=2)),
                ('sub_lacture_hours', models.IntegerField(default=0)),
                ('sub_tutorial_hours', models.IntegerField(default=0)),
                ('sub_practical_hours', models.IntegerField(default=0)),
                ('sub_category', models.CharField(default='Program Core', max_length=110)),
                ('sub_theory_mid1', models.IntegerField(default=0)),
                ('sub_theory_mid2', models.IntegerField(default=0)),
                ('sub_theory_micro', models.IntegerField(default=0)),
                ('sub_theory_PA', models.IntegerField(default=0)),
                ('sub_theory_ESE', models.IntegerField(default=0)),
                ('sub_prctical_PA', models.IntegerField(default=0)),
                ('sub_prctical_ESE', models.IntegerField(default=0)),
                ('sub_sem', models.IntegerField(default=0)),
                ('sub_credit', models.IntegerField(default=0)),
                ('sub_academic_term', models.CharField(max_length=5)),
                ('sub_pdf', models.FileField(upload_to='home/images/')),
                ('Assigned_Sub_Faculty', models.ForeignKey(default=11, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.faculty_records')),
            ],
        ),
    ]
