# Generated by Django 4.2.5 on 2023-09-25 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtuexam',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gtuexam',
            name='sub_code',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='main.sub_syllabus'),
        ),
    ]
