# Generated by Django 4.2.5 on 2023-12-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gtuexam_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_syllabus',
            name='sub_pdf',
            field=models.FileField(upload_to='home/pdfs/syllabus'),
        ),
    ]
