# Generated by Django 5.0.6 on 2024-07-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sub_syllabus_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_syllabus',
            name='type',
        ),
        migrations.AddField(
            model_name='gtuexam',
            name='type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('REMEDIAL', 'Remedial')], default='REGULAR', max_length=10),
        ),
    ]
