# Generated by Django 4.2.5 on 2023-09-25 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_records_delete_hello'),
        ('home', '0010_remove_syllabus_sub_assigned_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='sub_assigned_faculty',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty_records'),
        ),
    ]
