# Generated by Django 4.2.5 on 2023-09-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_syllabus_sub_assigned_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='sub_assigned_faculty',
            field=models.IntegerField(default=12),
        ),
    ]
