# Generated by Django 4.2.5 on 2023-09-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_sub_syllabus_delete_syllabus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_syllabus',
            name='sub_assigned_faculty',
        ),
    ]
