# Generated by Django 4.2.5 on 2023-12-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student_app', '0001_initial'),
        ('faculty', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_marks',
            name='Assigned_Sub_Faculty',
            field=models.ForeignKey(default=11, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.faculty_records'),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='student',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='Student_app.student'),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.sub_syllabus'),
        ),
    ]
