# Generated by Django 4.2.5 on 2023-09-25 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0002_alter_student_marks_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_marks',
            name='stu_enroll',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Student_app.student'),
        ),
    ]
