# Generated by Django 5.0.6 on 2024-07-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='detained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='Failed',
            field=models.BooleanField(default=False),
        ),
    ]
