# Generated by Django 5.0.6 on 2024-07-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0003_student_detained_student_marks_failed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='detained',
            new_name='is_detained',
        ),
        migrations.RenameField(
            model_name='student_marks',
            old_name='Failed',
            new_name='is_failed',
        ),
    ]
