# Generated by Django 5.0.6 on 2024-07-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0004_rename_detained_student_is_detained_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_detained',
        ),
        migrations.RemoveField(
            model_name='student_marks',
            name='is_failed',
        ),
        migrations.AddField(
            model_name='student',
            name='is_passed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='is_passed',
            field=models.BooleanField(default=True),
        ),
    ]
