# Generated by Django 5.0.6 on 2024-07-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0005_remove_student_is_detained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_marks',
            name='id',
            field=models.CharField(default='hello', max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
