# Generated by Django 5.0.6 on 2024-07-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0006_alter_student_marks_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_marks',
            name='year',
            field=models.CharField(default='2022', max_length=4),
        ),
    ]
