# Generated by Django 5.0.6 on 2024-07-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0007_student_marks_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_marks',
            name='save_marks',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student_marks',
            name='stu_practical_ESE',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_marks',
            name='stu_practical_PA',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_marks',
            name='stu_theory_ESE',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_marks',
            name='stu_theory_PA',
            field=models.IntegerField(),
        ),
    ]
