# Generated by Django 5.0.6 on 2024-07-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0008_student_marks_save_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_marks',
            name='save_marksop',
            field=models.BooleanField(default=False),
        ),
    ]
