# Generated by Django 5.0.6 on 2024-07-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0009_student_marks_save_marksop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_marks',
            name='save_marksop',
        ),
    ]
