# Generated by Django 5.0.6 on 2024-07-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0010_remove_student_marks_save_marksop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_marks',
            old_name='save_marks',
            new_name='marks_entered',
        ),
        migrations.AlterField(
            model_name='student_marks',
            name='stu_practical_ESE',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_marks',
            name='stu_practical_PA',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_marks',
            name='stu_theory_ESE',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_marks',
            name='stu_theory_PA',
            field=models.IntegerField(default=0),
        ),
    ]
